### ISSUE TITLE
ERROR with tabix_selector in PREPARE_REPEATS subworkflow 

### ISSUE THREAD

**Issue by BethYates** [sanger-tol/insdcdownload#22]
### Description of the bug

The pipeline fails on the PREPARE_REPEATS:TABIX_TABIX_TBI process. The calculation in the PREPARE_REPEATS subworkflow that works out if `tbi_and_csi` indexing can be used or if `only_csi` indexing can be used does not appear to be working when the pipeline is downloading the Corroboree frog `Pseudophryne corroboree` genome, `GCA_028390025.1 ` https://www.ebi.ac.uk/ena/browser/view/GCA_028390025.1

### Command used and terminal output

```console
nextflow run sanger-tol/insdcdownload --assembly_accession GCA_028390025.1 --assembly_name aPseCor3.hap2 -r 1.1.0 -profile sanger,singularity

ERROR ~ Error executing process > 'SANGERTOL_INSDCDOWNLOAD:INSDCDOWNLOAD:PREPARE_REPEATS:TABIX_TABIX_TBI (GCA_028390025.1.masked.ncbi)'

Caused by:
  Process `SANGERTOL_INSDCDOWNLOAD:INSDCDOWNLOAD:PREPARE_REPEATS:TABIX_TABIX_TBI (GCA_028390025.1.masked.ncbi)` terminated with an error exit status (1)

Command executed:

  tabix --preset bed GCA_028390025.1.masked.ncbi.bed.gz
  
  cat <<-END_VERSIONS > versions.yml
  "SANGERTOL_INSDCDOWNLOAD:INSDCDOWNLOAD:PREPARE_REPEATS:TABIX_TABIX_TBI":
      tabix: $(echo $(tabix -h 2>&1) | sed 's/^.*Version: //; s/ .*$//')
  END_VERSIONS

Command exit status:
  1

Command output:
  (empty)

Command error:
  [E::hts_idx_check_range] Region 536869515..536870967 cannot be stored in a tbi index. Try using a csi index
  tbx_index_build failed: GCA_028390025.1.masked.ncbi.bed.gz
```

**Comment by tkchafin** [comment]
I think this was fixed in https://github.com/sanger-tol/insdcdownload/pull/16 -- is there a reason you need 1.1.0 or could you try re-running with 2.0.0?

**Comment by BethYates** [comment]
Re-running with 2.0.0 works - thanks.

**Comment by BethYates** [comment]
Fix already made in newer version
